config/routes.rb
Rails.application.routes.draw do
  get 'timesheets/index'
  get 'timesheets/show'
  root "users#index"
  devise_for :users

  resources :users

  resources :timesheets

  # get 'timesheets', to: "timesheets#index"
  post 'create_clock_in_entry', to: "timesheets#create_clock_in_entry"
  post 'create_clock_out_entry', to: "timesheets#create_clock_out_entry"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users  #[Admin, Teacher]
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :timesheets
  belongs_to :role

  validates_presence_of :first_name, :last_name, :email
  validates :email, presence: true, format: Devise.email_regexp
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
   
    def configure_permitted_parameters
        attributes = [:first_name, :last_name, :role_id]
        devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    end

    def after_sign_in_path_for(user)
        user_path(current_user)
    end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :set_timesheet, only: [:edit, :update, :destroy]

  def index
    @timesheets = current_user.timesheets.order(clock_in: :desc)
  end

  def show
    @timesheet = current_user.timesheets.order(clock_in: :desc)
    @teacher = User.find(params[:id]) ? User.find(params[:id]) : User.find(params[:user_id])
  end

  def edit
  end

  def update
    timesheet_params[:clock_in].blank? ? timesheet_params[:clock_in] = @timesheet.clock_in : timesheet_params[:clock_in].to_datetime
    timesheet_params[:clock_out].blank? ? timesheet_params[:clock_out] = @timesheet.clock_out : timesheet_params[:clock_out].to_datetime

    if @timesheet.update(timesheet_params)
      flash[:notice] = "Timesheet detail updated successfully!"
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def create_clock_in_entry
    # byebug
    if !timesheet_present?
      @timesheet = current_user.timesheets.create(clock_in: Time.now, clock_out: nil, date: Date.today)
      flash[:notice] = "Time sheet successfully updated!"
    elsif timesheet_present? && !last_timesheet_entry.clock_out.nil?
      @timesheet = current_user.timesheets.create(clock_in: Time.now, clock_out: nil, date: Date.today)
      flash[:notice] = "Time sheet successfully updated!"
    elsif timesheet_present? && last_timesheet_entry.clock_out.nil?
      @timesheet = last_timesheet_entry.update(clock_out: Time.now)
      flash[:notice] = "Time sheet successfully updated!"
    else
      flash[:notice] = "You have not clocked out from last time yet. Clock out first to create a new entry."
    end
    redirect_to user_path(current_user)
  end

  def create_clock_out_entry
    if last_timesheet_entry.clock_out.nil?
      last_timesheet_entry.update(clock_out: Time.now)
      flash[:notice] = "Time sheet successfully updated!"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Your last clock out is already uo to date!"
    end
  end

  def destroy
    @timesheet = Timesheet.find(params[:id])
    if @timesheet.destroy
      flash[:notice] = "Deleted successfully"
      redirect_to user_path(current_user)
    end
  end

  private
  def timesheet_params
    params.require(:timesheet).permit(:clock_in, :clock_out)
  end

  def set_timesheet
    @timesheet = Timesheet.find(params[:id])
  end

  def timesheet_present?
    current_user.timesheets.present?
  end

  def last_timesheet_entry
    current_user.timesheets.last
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @last_timesheet = User.all.map {|user| user.timesheets.last}
    @current_user_timesheets = Timesheet.where(user_id: current_user.id)
  end

  def edit
  end

  def update
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_name(user)
        user.first_name + ' ' + user.last_name
    end
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cards.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6">
    <div class="card-group">
        <div class="card text-center">    
            <div class="card-body">
            <h5 class="card-title">93% of customers</h5>
            <p class="card-text">say our childcare app saves time on reporting.</p>
            </div>
        </div>
        <div class="card text-center">   
            <div class="card-body">
            <h5 class="card-title">98% of parents</h5>
            <p class="card-text">say HiMama adds to their overall satisfaction with their child care provider.</p>
            </div>
        </div>
        <div class="card text-center">   
            <div class="card-body">
            <h5 class="card-title">97% of customers</h5>
            <p class="card-text">say our app for daycares makes their programs stand out from others.</p>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "HiMama", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if !user_signed_in? %>
            <li class="nav-item active">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% else %>
            <%= link_to 'Home', user_path(current_user), class: 'nav-link' %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% end %>
        <li class="nav-item active">
            <%= link_to 'About us', "https://www.himama.com/about", class: 'nav-link' %>
        </li>
    </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container-fluid" id="home-container">
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>', '', {
            "closeButton": true,
            "positionClass": "toast-top-center", 
            "onclick": null, 
            "showDuration": "300", 
            "hideDuration": "1000", 
            "timeOut": "5000", 
            "extendedTimeOut": "1000", 
            "showEasing": "swing", 
            "hideEasing": "linear", 
            "showMethod": "fadeIn", 
            "progressBar": true,
            "hideMethod": "fadeOut" });
      <% end %>
      </script>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/timesheets/_timesheet.html.erb
<h2>Timesheet entries</h2>
<table class="table table-bordered table-hover text-center">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Clock in time</th>
            <th scope="col">Clock out time</th>
        </tr>
    </thead>
    <tbody>
        <% timesheets.each do |timesheet| %>      
            <tr>
                <td><%= timesheet.date.to_date %></td>
                <td><%= timesheet.clock_in %></td>
                <td><%= timesheet.clock_out %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/timesheets/edit.html.erb
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">Clock in: <%= @timesheet.clock_in%></li>
  <li class="list-group-item">Clock out: <%= @timesheet.clock_out%></li>
</ul>

<%= form_with(model: @timesheet, local: true) do |f| %>
    <div class="field mb-3">
        <%= f.label :clock_in %></br>
        <%= f.datetime_field :clock_in, as: :datetime, value: f.object.clock_in.try(:strftime,"%m/%d/%Y") %>
    </div>

    <div class="field mb-3">
        <%=  f.label :clock_out %></br>
        <%= f.datetime_field :clock_out, as: :datetime, value: f.object.clock_in.try(:strftime,"%m/%d/%Y") %>
    </div>

    <div class="actions mb-3">
        <%= f.submit %>
    </div>
<% end %>

app/views/timesheets/show.html.erb
<h2>Timesheet entries for <%= user_name(@teacher)%> </h2>
<table class="table table-bordered table-hover text-center">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Clock in time</th>
            <th scope="col">Clock out time</th>
            <% if current_user.role.name == "Admin" %>
                <th colspan=2 scope="col">Actions</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @teacher.timesheets.each do |timesheet| %>
            <tr>
                <td><%= timesheet.date.to_date %></td>
                <td><%= timesheet.clock_in %></td>
                <td><%= timesheet.clock_out %></td>
                <% if current_user.role_id == 1 %>
                    <td><%= link_to "Edit", edit_timesheet_path(timesheet) %></td>
                    <td><%= link_to "Destroy", timesheet_path(timesheet.id, user_id: timesheet.user.id), method: :delete, data: { confirm: 'Are you sure?'}  %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_teachers.html.erb
<h3>List of Teachers and last time entries</h3>
<div class="table-responsive">
    <table class="table table-bordered table-hover text-center">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Last clock in time</th>
                <th scope="col">Last clock out time</th>
                <th colspan=3 scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @last_timesheet.each do |timesheet| %>
                <tr>
                    <td><%= user_name(timesheet.user) %></td>
                    <td><%= timesheet.clock_in %></td>
                    <td><%= timesheet.clock_out %></td>
                    <td><%= link_to "View timesheet", timesheet_path(id: timesheet.user_id) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="jumbotron" id="jumbotron_index"></div>
<h1><center>Welcome to HiMama Daycare platform</center></h1>
<%= render "layouts/cards" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h2><%= "Welcome #{current_user.first_name}"%></h2>
<div class="row">
    <div class="btn-group">
        <div class="col-md-6 clock-action"><%= button_to "Clock in", create_clock_in_entry_path, class: "btn btn-outline-primary btn-lg" %></div>
        <div class="col-md-6 clock-action"><%= button_to "Clock out", create_clock_out_entry_path, class: "btn btn-outline-danger btn-lg" %></div>
    </div>
</div>

<div class="row">
    <div class="container-fluid">
    <% if current_user.role.name == "Admin" %>
        <%= render partial: 'teachers' %>
    <% else %>
        <%= render partial: 'timesheets/timesheet', locals: {timesheets: @current_user_timesheets} %>
    <% end %></div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>